version: "2"
checks:
  method-lines:
    config:
      threshold: 30
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config: 
      config: .eslintrc.json
    checks:
      compat/compat:
        enabled: false
      indent:
        enabled: false
exclude_patterns:
  - ".github/"
  - "doc/"
  - "docs/"
  - "test/"
  - "types/"
  - "**/node_modules/"
  - "src/report/**/*.template.js"