test_async_node_latest:
  image: node:latest
  cache:
    paths:
    - node_modules/
  script:
   - npm install
   - npm run lint
   - npm run nsp
   - npm run cover

test_async_node_4:
  image: node:4
  cache:
    paths:
    - node_modules/
  script:
   - npm install
   - npm run lint
   - npm run nsp
   - npm run cover
