cache:
  key: "$CI_JOB_NAME"
  untracked: true
  paths:
    - node_modules

test_async_node_latest:
  image: node:latest
  script:
   - npm install
   - npm run lint
   - npm run lint:types
   - npm run depcruise
   - npm run nsp
   - npm run test:cover
  except:
   - tags

test_async_node_8:
  image: node:8
  script:
   - npm install
   - npm run test:cover
  except:
   - tags

test_async_node_6:
  image: node:6
  script:
   - npm install
   - npm run test:cover
  except:
   - tags
   - master

# publish:
#  image: node:latest
#  script:
#    - echo 'npm publish'
#  only:
#    - tags
