# we might want to add latest - 1 && latest - 2 to this
image: 
    node:latest
    node:latest - 1 
    node:latest - 2

cache:
  paths:
  - node_modules/

test_async:
  script:
   - npm install
   - npm run lint
   - npm run nsp
   - npm run cover
