sudo: false

language: node_js

node_js:
  - "6"
  - "8"
  - "9"

install:
  - npm install

script:
  - make lint depcruise cover
  - npm run nsp

branches:
  except:
    - gh-pages

cache:
  directories:
    - node_modules
