sudo: false

language: node_js

node_js:
  - "6"
  - "8"
  - "10"
  - "11"

install:
  - npm install

script:
  - make depcruise
  - 'npm run test:glob && npm run test:cover'
  - 'if test `node --version | cut -c 2` = 10; then npm run nsp && npm run lint; fi'

branches:
  except:
    - gh-pages

cache:
  directories:
    - node_modules
